import Head from 'next/head'
import Navbar from '../pages/components/navbar'
import Main from '../pages/components/FrontPage'
import AboutMe from '../pages/components/AboutMe'
import Skills from '../pages/components/Skills'
import Projects from '../pages/components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Isaac Sun Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Navbar/>
      <Main/>
      <AboutMe/>
      <Skills/>
      <Projects/>
    </div>
  )
}
